### ISSUE TITLE
AssignCommand executes despite showing an error message

### ISSUE THREAD

**Issue by maertan** [AY2425S1-CS2103T-T12-2/tp#190]
for example, if index 1 is a blank wedding and the following commands are input:
assign 1 c/1
assign 1 c/1 2

the message "Person has already been added" would be shown, but person 2 would still be added to the wedding

Somehow this only happens sometimes, after spamming "assign 1 c/1 2"

**Comment by yxshrk** [comment]
I think the recent PR should have fixed this too.
