### ISSUE TITLE
Update display after deleting a wedding from inside its view

### ISSUE THREAD

**Issue by adipanda2002** [AY2425S1-CS2103T-T12-2/tp#197]
Consider the case where I am in a wedding view (eg: `view 3`). If I do a `deletew 3`, the now deleted wedding view remains on screen. We can consider auto-running a `list` command so that all contacts are displayed instead of leaving the user on a wedding view that by right has now been deleted

**Comment by kikokidayo** [comment]
Yup will fix it later today
