### ISSUE TITLE
[PE-D][Tester D] Inability to add non alphanumeric characters to names

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#273]
![image.png](https://raw.githubusercontent.com/nathanshew/ped/main/files/c740ce60-a81c-4e3b-9d67-a8fbd45bd7b6.png)

Certain Singaporeans have names which include @, and brackets (particularly the Chinese who wish to include their chinese names)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: nathanshew/ped#5

**Comment by adipanda2002** [comment]
uPDATE faQ
