### ISSUE TITLE
[PE-D][Tester D] Inaccuracy of guide in clear command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-2/tp#277]
![image.png](https://raw.githubusercontent.com/nathanshew/ped/main/files/e371fff0-1a15-469a-a2d5-ac070374dc84.png)
I input a small y and it cleared my data, which is not "Y" nor "Yes"

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nathanshew/ped#7

**Comment by adipanda2002** [comment]
Duplicate
