### ISSUE TITLE
[PE-D][Tester B] Error message as person already exist instead of phone number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-2/tp#280]
When edit changes a phone number to one that already exist error message is person already exist, instead of phone number already exist as it does when adding a person with same phone number
![Screenshot 2024-11-08 at 4.53.25 PM.png](https://raw.githubusercontent.com/Plishh/ped/main/files/412a0d63-b6b3-4f60-96f0-e91aa7d2fba7.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Plishh/ped#6

**Comment by adipanda2002** [comment]
Contact and Person are used interchangeably (UG Glossary) - Iggy
Add message in edit UG saying you can't edit a person's number to one that someone else has - Adi
