### ISSUE TITLE
[PE-D][Tester D] Storing random dates

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#284]
![image.png](https://raw.githubusercontent.com/nathanshew/ped/main/files/de63b54a-6469-4dc3-a023-81de43283e16.png)

Does not make sense that I can store 0001 but not 0000

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: nathanshew/ped#9

**Comment by adipanda2002** [comment]
The year 0000 doesn't exist
