### ISSUE TITLE
[PE-D][Tester D] Incorrect error thrown 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#297]
![image.png](https://raw.githubusercontent.com/nathanshew/ped/main/files/d2cf61ac-e0cd-41f2-86d5-3a57529a73cc.png)

(it is a positive integer)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nathanshew/ped#12

**Comment by adipanda2002** [comment]
Can't change anything to fix this
