### ISSUE TITLE
[PE-D][Tester E] Long addresses do not display in full

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#299]
Reproducible by editing a person's address to consist of 50 `W`s. (W is a long character).

![image.png](https://raw.githubusercontent.com/notnotmax/ped/main/files/cdc3bd81-a1af-48f5-b49d-a18cf475b1fb.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: notnotmax/ped#11

**Comment by adipanda2002** [comment]
Duplicate
