### ISSUE TITLE
[PE-D][Tester B] there is no tag but unknown command returned instead

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#306]
![Screenshot 2024-11-08 at 5.31.47 PM.png](https://raw.githubusercontent.com/Plishh/ped/main/files/31b8a9d6-0adf-4c5d-aceb-74bc70100e2a.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Plishh/ped#8

**Comment by adipanda2002** [comment]
Tester did not put space between command and contact index
