### ISSUE TITLE
[PE-D][Tester A] Contact assigned to a wedding can be deleted in the contact list

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#321]
![Screenshot 2024-11-08 at 7.12.36 PM.png](https://raw.githubusercontent.com/JellyPenguinnn/ped/main/files/faec8323-7e4b-4676-8d0e-4d1bccadaeac.png)

![Screenshot 2024-11-08 at 7.12.55 PM.png](https://raw.githubusercontent.com/JellyPenguinnn/ped/main/files/52fd0904-8011-497a-8b11-e042219ff6ba.png)

- The contact assigned to the wedding shouldn't be directly deleted from the contact list.

- May show an error message that shows the contact is in the wedding.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: JellyPenguinnn/ped#10

**Comment by adipanda2002** [comment]
Distinguish between delete and unassign in the UG

- suggested: add a warning in delete
