### ISSUE TITLE
[PE-D][Tester B] Missing multiplicities

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#329]
![Screenshot 2024-11-08 at 8.05.01 PM.png](https://raw.githubusercontent.com/Plishh/ped/main/files/7a811b44-9322-4839-9778-4e6d116c8f94.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Plishh/ped#10

**Comment by kikokidayo** [comment]
Does the same apply to your model diagram also cos you didn't add multiplicities for some object types @ignatiusoey09
