### ISSUE TITLE
[PE-D][Tester C] F1 Shortcut for Help Command Doesn't Work

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#330]
The F1 keyboard shortcut for the Help command does not function as expected. Pressing F1 does not open the help documentation or trigger any response

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: iamdiluxedbutcooler/ped#23

**Comment by adipanda2002** [comment]
Testeed both windows and mac, seems to work fine :|
