### ISSUE TITLE
[PE-D][Tester C] Inconsistent Use of "Person" and "Contact" in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#331]
The User Guide inconsistently uses the terms "person" and "contact" to refer to the same entity. This lack of consistency can confuse users, as it is unclear whether the terms refer to different concepts or are used interchangeably.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: iamdiluxedbutcooler/ped#24

**Comment by adipanda2002** [comment]
Add to UG glossary

**Comment by adipanda2002** [comment]
Not required anymore, there is not more mention of person in the UG
