### ISSUE TITLE
[PE-D][Tester C] Outdated "AddressBook" References in Developer Guide Need Refactoring to "PlanPerfect"

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-2/tp#338]
Throughout the Developer Guide, terms like "AddressBook" still appear in code snippets, class names, file names, and explanations. Since the application has been rebranded as "PlanPerfect," these references should be updated to reflect the new name. 

-------------
Labels: `type.DocumentationBug` `severity.High`
original: iamdiluxedbutcooler/ped#30

**Comment by adipanda2002** [comment]
We did not change the class names from the original code, so not required
