### ISSUE TITLE
Add more comprehensive test cases

### ISSUE THREAD

**Issue by ignatiusoey09** [AY2425S1-CS2103T-T12-2/tp#81]
Add test cases to increase test coverage

**Comment by ignatiusoey09** [comment]
Added tests for Tag, TagCommand and TagCommandParser

**Comment by kikokidayo** [comment]
Added tests for ClearCommand, ActualClearCommand, and ActualClearCommandParser

**Comment by maertan** [comment]
Added tests for FilterCommand, FilterCommandParser, PersonTaggedWithPredicate, AddressBookParser

**Comment by adipanda2002** [comment]
Added/Modified test cases for edit and help

**Comment by adipanda2002** [comment]
#64 #100
